// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

listener http:Listener ep0 = new (9090);

@http:ServiceConfig {treatNilableAsOptional: true}
service / on ep0 {
    # Allows you to delete a task
    #
    # + xeroTenantId - Xero identifier for Tenant
    # + projectId - You can specify an individual project by appending the projectId to the endpoint
    # + taskId - You can specify an individual task by appending the id to the endpoint
    # + return - returns can be any of following types 
    # http:NoContent (Success - return response 204 no content)
    # http:BadRequest (A failed request due to validation error)
    resource function delete Projects/[string projectId]/Tasks/[string taskId](@http:Header {name: "Xero-Tenant-Id"} string xeroTenantId) returns http:NoContent|ErrorBadRequest {
        return http:NO_CONTENT;
    }

    # Deletes a time entry for a specific project
    #
    # + xeroTenantId - Xero identifier for Tenant
    # + projectId - You can specify an individual project by appending the projectId to the endpoint
    # + timeEntryId - You can specify an individual task by appending the id to the endpoint
    # + return - returns can be any of following types 
    # http:NoContent (Success - return response 204 no content)
    # http:BadRequest (A failed request due to validation error)
    resource function delete Projects/[string projectId]/Time/[string timeEntryId](@http:Header {name: "Xero-Tenant-Id"} string xeroTenantId) returns http:NoContent|ErrorBadRequest {
        return http:NO_CONTENT;
    }

    # Retrieves all projects
    #
    # + xeroTenantId - Xero identifier for Tenant
    # + projectIds - Search for all projects that match a comma separated list of projectIds
    # + contactID - Filter for projects for a specific contact
    # + states - Filter for projects in a particular state (INPROGRESS or CLOSED)
    # + page - set to 1 by default. The requested number of the page in paged response - Must be a number greater than 0
    # + pageSize - Optional, it is set to 50 by default. The number of items to return per page in a paged response - Must be a number between 1 and 500
    # + return - returns can be any of following types 
    # http:Ok (OK/success, returns a list of project objects)
    # http:BadRequest (A failed request due to validation error)
    resource function get Projects(@http:Header {name: "Xero-Tenant-Id"} string xeroTenantId, string[]? projectIds, string? contactID, string? states, int page = 1, int pageSize = 50) returns ProjectList|ErrorBadRequest {
        Project project = {
            projectId: "254529e0-2d7f-4b5f-a1ae-2b8b3a8d1c01",
            contactId: "1ed7e1ba-f6a2-4a4f-8b1c-3d5e6f7a8b90",
            name: "Website Redesign",
            currencyCode: "USD",
            minutesLogged: 360,
            totalTaskAmount: {currency: "USD", value: 1200},
            totalInvoiced: {currency: "USD", value: 600},
            estimate: {currency: "USD", value: 2400},
            deadlineUtc: "2026-12-31T00:00:00Z",
            status: "INPROGRESS"
        };
        ProjectList list = {pagination: {page: 1, pageSize: 50, pageCount: 1, itemCount: 1}, items: [project]};
        return list;
    }

    # Retrieves a single project
    #
    # + xeroTenantId - Xero identifier for Tenant
    # + projectId - You can specify an individual project by appending the projectId to the endpoint
    # + return - returns can be any of following types 
    # http:Ok (OK/success, returns the specified project object)
    # http:BadRequest (A failed request due to validation error)
    resource function get Projects/[string projectId](@http:Header {name: "Xero-Tenant-Id"} string xeroTenantId) returns Project|ErrorBadRequest {
        Project project = {
            projectId: "254529e0-2d7f-4b5f-a1ae-2b8b3a8d1c01",
            contactId: "1ed7e1ba-f6a2-4a4f-8b1c-3d5e6f7a8b90",
            name: "Website Redesign",
            currencyCode: "USD",
            minutesLogged: 360,
            totalTaskAmount: {currency: "USD", value: 1200},
            totalInvoiced: {currency: "USD", value: 600},
            estimate: {currency: "USD", value: 2400},
            deadlineUtc: "2026-12-31T00:00:00Z",
            status: "INPROGRESS"
        };
        return project;
    }

    # Retrieves all project tasks
    #
    # + xeroTenantId - Xero identifier for Tenant
    # + projectId - You can specify an individual project by appending the projectId to the endpoint
    # + page - Set to 1 by default. The requested number of the page in paged response - Must be a number greater than 0
    # + pageSize - Optional, it is set to 50 by default. The number of items to return per page in a paged response - Must be a number between 1 and 500
    # + taskIds - Search for all tasks that match a comma separated list of taskIds, i.e. GET https://.../tasks?taskIds={taskID},{taskID}
    # + return - returns can be any of following types 
    # http:Ok (OK/success, returns a list of task objects)
    # http:BadRequest (A failed request due to validation error)
    resource function get Projects/[string projectId]/Tasks(@http:Header {name: "Xero-Tenant-Id"} string xeroTenantId, int? page, int? pageSize, string? taskIds, ChargeType? chargeType) returns TaskList|ErrorBadRequest {
        Task task = {
            taskId: "7c1f2a3b-4d5e-6f70-8192-a3b4c5d6e7f8",
            projectId: "254529e0-2d7f-4b5f-a1ae-2b8b3a8d1c01",
            name: "Design mockups",
            chargeType: "TIME",
            rate: {currency: "USD", value: 120},
            estimateMinutes: 480,
            totalMinutes: 360,
            minutesInvoiced: 180,
            minutesToBeInvoiced: 180,
            nonChargeableMinutes: 0
        };
        TaskList list = {pagination: {page: 1, pageSize: 50, pageCount: 1, itemCount: 1}, items: [task]};
        return list;
    }

    # Retrieves a single project task
    #
    # + xeroTenantId - Xero identifier for Tenant
    # + projectId - You can specify an individual project by appending the projectId to the endpoint
    # + taskId - You can specify an individual task by appending the taskId to the endpoint, i.e. GET https://.../tasks/{taskID}
    # + return - returns can be any of following types 
    # http:Ok (OK/success, returns the specified task object)
    # http:BadRequest (A failed request due to validation error)
    resource function get Projects/[string projectId]/Tasks/[string taskId](@http:Header {name: "Xero-Tenant-Id"} string xeroTenantId) returns Task|ErrorBadRequest {
        Task task = {
            taskId: "7c1f2a3b-4d5e-6f70-8192-a3b4c5d6e7f8",
            projectId: "254529e0-2d7f-4b5f-a1ae-2b8b3a8d1c01",
            name: "Design mockups",
            chargeType: "TIME",
            rate: {currency: "USD", value: 120},
            estimateMinutes: 480,
            totalMinutes: 360,
            minutesInvoiced: 180,
            minutesToBeInvoiced: 180,
            nonChargeableMinutes: 0
        };
        return task;
    }

    # Retrieves all time entries associated with a specific project
    #
    # + xeroTenantId - Xero identifier for Tenant
    # + projectId - Identifier of the project, that the task (which the time entry is logged against) belongs to
    # + userId - The xero user identifier of the person who logged time
    # + taskId - Identifier of the task that time entry is logged against
    # + invoiceId - Finds all time entries for this invoice
    # + contactId - Finds all time entries for this contact identifier
    # + page - Set to 1 by default. The requested number of the page in paged response - Must be a number greater than 0
    # + pageSize - Optional, it is set to 50 by default. The number of items to return per page in a paged response - Must be a number between 1 and 500
    # + states - Comma-separated list of states to find. Will find all time entries that are in the status of whatever is specified
    # + isChargeable - Finds all time entries which relate to tasks with the charge type `TIME` or `FIXED`
    # + dateAfterUtc - ISO 8601 UTC date. Finds all time entries on or after this date filtered on the `dateUtc` field
    # + dateBeforeUtc - ISO 8601 UTC date. Finds all time entries on or before this date filtered on the `dateUtc` field
    # + return - returns can be any of following types 
    # http:Ok (OK/success, returns a list of time entry objects)
    # http:BadRequest (A failed request due to validation error)
    resource function get Projects/[string projectId]/Time(@http:Header {name: "Xero-Tenant-Id"} string xeroTenantId, string? userId, string? taskId, string? invoiceId, string? contactId, int? page, int? pageSize, string[]? states, boolean? isChargeable, string? dateAfterUtc, string? dateBeforeUtc) returns TimeEntryList|ErrorBadRequest {
        TimeEntry entry = {
            timeEntryId: "9a8b7c6d-5e4f-3a2b-1c0d-e9f8a7b6c5d4",
            projectId: "254529e0-2d7f-4b5f-a1ae-2b8b3a8d1c01",
            taskId: "7c1f2a3b-4d5e-6f70-8192-a3b4c5d6e7f8",
            userId: "b1c2d3e4-f5a6-4789-9abc-def012345678",
            dateUtc: "2026-10-05T09:00:00Z",
            dateEnteredUtc: "2026-10-05T17:30:00Z",
            duration: 90,
            description: "Homepage wireframes"
        };
        TimeEntryList list = {pagination: {page: 1, pageSize: 50, pageCount: 1, itemCount: 1}, items: [entry]};
        return list;
    }

    # Retrieves a single time entry for a specific project
    #
    # + xeroTenantId - Xero identifier for Tenant
    # + projectId - You can specify an individual project by appending the projectId to the endpoint
    # + timeEntryId - You can specify an individual time entry by appending the id to the endpoint
    # + return - returns can be any of following types 
    # http:Ok (OK/success, returns the specified time entry)
    # http:BadRequest (A failed request due to validation error)
    resource function get Projects/[string projectId]/Time/[string timeEntryId](@http:Header {name: "Xero-Tenant-Id"} string xeroTenantId) returns TimeEntry|ErrorBadRequest {
        TimeEntry entry = {
            timeEntryId: "9a8b7c6d-5e4f-3a2b-1c0d-e9f8a7b6c5d4",
            projectId: "254529e0-2d7f-4b5f-a1ae-2b8b3a8d1c01",
            taskId: "7c1f2a3b-4d5e-6f70-8192-a3b4c5d6e7f8",
            userId: "b1c2d3e4-f5a6-4789-9abc-def012345678",
            dateUtc: "2026-10-05T09:00:00Z",
            dateEnteredUtc: "2026-10-05T17:30:00Z",
            duration: 90,
            description: "Homepage wireframes"
        };
        return entry;
    }

    # Retrieves a list of all project users
    #
    # + xeroTenantId - Xero identifier for Tenant
    # + page - set to 1 by default. The requested number of the page in paged response - Must be a number greater than 0
    # + pageSize - Optional, it is set to 50 by default. The number of items to return per page in a paged response - Must be a number between 1 and 500
    # + return - returns can be any of following types 
    # http:Ok (OK/success, returns a list of project users)
    # http:BadRequest (A failed request due to validation error)
    resource function get ProjectsUsers(@http:Header {name: "Xero-Tenant-Id"} string xeroTenantId, int page = 1, int pageSize = 50) returns ProjectUserList|ErrorBadRequest {
        ProjectUser user = {
            userId: "b1c2d3e4-f5a6-4789-9abc-def012345678",
            name: "Jordan Lee",
            email: "jordan.lee@acmecorp.test"
        };
        ProjectUserList list = {pagination: {page: 1, pageSize: 50, pageCount: 1, itemCount: 1}, items: [user]};
        return list;
    }

    # Updates the status of a specific project
    #
    # + xeroTenantId - Xero identifier for Tenant
    # + idempotencyKey - This allows you to safely retry requests without the risk of duplicate processing. 128 character max
    # + projectId - You can specify an individual project by appending the projectId to the endpoint
    # + payload - Update the status of an existing Project 
    # + return - returns can be any of following types 
    # http:NoContent (Success - return response 204 no content)
    # http:BadRequest (A failed request due to validation error)
    resource function patch Projects/[string projectId](@http:Header {name: "Xero-Tenant-Id"} string xeroTenantId, @http:Header {name: "Idempotency-Key"} string? idempotencyKey, @http:Payload ProjectPatch payload) returns http:NoContent|ErrorBadRequest {
        return http:NO_CONTENT;
    }

    # Create one or more new projects
    #
    # + xeroTenantId - Xero identifier for Tenant
    # + idempotencyKey - This allows you to safely retry requests without the risk of duplicate processing. 128 character max
    # + payload - Create a new project with ProjectCreateOrUpdate object 
    # + return - returns can be any of following types 
    # http:Created (OK/success, returns the new project object)
    # http:BadRequest (A failed request due to validation error)
    resource function post Projects(@http:Header {name: "Xero-Tenant-Id"} string xeroTenantId, @http:Header {name: "Idempotency-Key"} string? idempotencyKey, @http:Payload ProjectCreateOrUpdate payload) returns Project|ErrorBadRequest {
        Project project = {
            projectId: "254529e0-2d7f-4b5f-a1ae-2b8b3a8d1c01",
            contactId: "1ed7e1ba-f6a2-4a4f-8b1c-3d5e6f7a8b90",
            name: "Website Redesign",
            currencyCode: "USD",
            minutesLogged: 360,
            totalTaskAmount: {currency: "USD", value: 1200},
            totalInvoiced: {currency: "USD", value: 600},
            estimate: {currency: "USD", value: 2400},
            deadlineUtc: "2026-12-31T00:00:00Z",
            status: "INPROGRESS"
        };
        return project;
    }

    # Allows you to create a task
    #
    # + xeroTenantId - Xero identifier for Tenant
    # + idempotencyKey - This allows you to safely retry requests without the risk of duplicate processing. 128 character max
    # + projectId - You can create a task on a specified projectId
    # + payload - The task object you are creating 
    # + return - returns can be any of following types 
    # http:Created (OK/success, returns the new task object)
    # http:BadRequest (A failed request due to validation error)
    resource function post Projects/[string projectId]/Tasks(@http:Header {name: "Xero-Tenant-Id"} string xeroTenantId, @http:Header {name: "Idempotency-Key"} string? idempotencyKey, @http:Payload TaskCreateOrUpdate payload) returns Task|ErrorBadRequest {
        Task task = {
            taskId: "7c1f2a3b-4d5e-6f70-8192-a3b4c5d6e7f8",
            projectId: "254529e0-2d7f-4b5f-a1ae-2b8b3a8d1c01",
            name: "Design mockups",
            chargeType: "TIME",
            rate: {currency: "USD", value: 120},
            estimateMinutes: 480,
            totalMinutes: 360,
            minutesInvoiced: 180,
            minutesToBeInvoiced: 180,
            nonChargeableMinutes: 0
        };
        return task;
    }

    # Creates a time entry for a specific project
    #
    # + xeroTenantId - Xero identifier for Tenant
    # + idempotencyKey - This allows you to safely retry requests without the risk of duplicate processing. 128 character max
    # + projectId - You can specify an individual project by appending the projectId to the endpoint
    # + payload - The time entry object you are creating 
    # + return - returns can be any of following types 
    # http:Ok (OK/success, returns the newly created time entry)
    # http:BadRequest (A failed request due to validation error)
    resource function post Projects/[string projectId]/Time(@http:Header {name: "Xero-Tenant-Id"} string xeroTenantId, @http:Header {name: "Idempotency-Key"} string? idempotencyKey, @http:Payload TimeEntryCreateOrUpdate payload) returns TimeEntryOk|ErrorBadRequest {
        TimeEntry entry = {
            timeEntryId: "9a8b7c6d-5e4f-3a2b-1c0d-e9f8a7b6c5d4",
            projectId: "254529e0-2d7f-4b5f-a1ae-2b8b3a8d1c01",
            taskId: "7c1f2a3b-4d5e-6f70-8192-a3b4c5d6e7f8",
            userId: "b1c2d3e4-f5a6-4789-9abc-def012345678",
            dateUtc: "2026-10-05T09:00:00Z",
            dateEnteredUtc: "2026-10-05T17:30:00Z",
            duration: 90,
            description: "Homepage wireframes"
        };
        return {body: entry};
    }

    # Updates a specific project
    #
    # + xeroTenantId - Xero identifier for Tenant
    # + idempotencyKey - This allows you to safely retry requests without the risk of duplicate processing. 128 character max
    # + projectId - You can specify an individual project by appending the projectId to the endpoint
    # + payload - Request of type ProjectCreateOrUpdate 
    # + return - returns can be any of following types 
    # http:NoContent (Success - return response 204 no content)
    # http:BadRequest (A failed request due to validation error)
    resource function put Projects/[string projectId](@http:Header {name: "Xero-Tenant-Id"} string xeroTenantId, @http:Header {name: "Idempotency-Key"} string? idempotencyKey, @http:Payload ProjectCreateOrUpdate payload) returns http:NoContent|ErrorBadRequest {
        return http:NO_CONTENT;
    }

    # Allows you to update a task
    #
    # + xeroTenantId - Xero identifier for Tenant
    # + idempotencyKey - This allows you to safely retry requests without the risk of duplicate processing. 128 character max
    # + projectId - You can specify an individual project by appending the projectId to the endpoint
    # + taskId - You can specify an individual task by appending the id to the endpoint
    # + payload - The task object you are updating 
    # + return - returns can be any of following types 
    # http:NoContent (OK/Success - return response 204 no content)
    # http:BadRequest (A failed request due to validation error)
    resource function put Projects/[string projectId]/Tasks/[string taskId](@http:Header {name: "Xero-Tenant-Id"} string xeroTenantId, @http:Header {name: "Idempotency-Key"} string? idempotencyKey, @http:Payload TaskCreateOrUpdate payload) returns http:NoContent|ErrorBadRequest {
        return http:NO_CONTENT;
    }

    # Updates a time entry for a specific project
    #
    # + xeroTenantId - Xero identifier for Tenant
    # + idempotencyKey - This allows you to safely retry requests without the risk of duplicate processing. 128 character max
    # + projectId - You can specify an individual project by appending the projectId to the endpoint
    # + timeEntryId - You can specify an individual time entry by appending the id to the endpoint
    # + payload - The time entry object you are updating 
    # + return - returns can be any of following types 
    # http:NoContent (Success - return response 204 no content)
    # http:BadRequest (A failed request due to validation error)
    resource function put Projects/[string projectId]/Time/[string timeEntryId](@http:Header {name: "Xero-Tenant-Id"} string xeroTenantId, @http:Header {name: "Idempotency-Key"} string? idempotencyKey, @http:Payload TimeEntryCreateOrUpdate payload) returns http:NoContent|ErrorBadRequest {
        return http:NO_CONTENT;
    }
}

// Service-mode response types. `bal openapi --mode client` collapses 4XX/5XX
// to `error` and never emits these, so they are defined here for the mock only.
public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type TimeEntryOk record {|
    *http:Ok;
    TimeEntry body;
|};

# Error returned by the Xero Projects API
public type Error record {
    # Array of Elements of validation Errors
    record {} modelState?;
    # Exception message
    string message?;
};
