// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;
import ballerina/os;
import ballerina/test;

final boolean isLiveServer = os:getEnv("IS_LIVE_SERVER") == "true";
final string serviceUrl = isLiveServer ? "https://api.xero.com/projects.xro/2.0" : "http://localhost:9090";
final string token = isLiveServer ? os:getEnv("XERO_ACCESS_TOKEN") : "test_token";
final string tenantId = isLiveServer ? os:getEnv("XERO_TENANT_ID") : "test-tenant-id";

final Client xeroProjects = check new ({
    auth: {token},
    httpVersion: isLiveServer ? http:HTTP_2_0 : http:HTTP_1_1
}, serviceUrl);

final string PROJECT_ID = isLiveServer ? os:getEnv("XERO_PROJECT_ID") : "254529e0-2d7f-4b5f-a1ae-2b8b3a8d1c01";
final string TASK_ID = isLiveServer ? os:getEnv("XERO_TASK_ID") : "7c1f2a3b-4d5e-6f70-8192-a3b4c5d6e7f8";
final string TIME_ENTRY_ID = isLiveServer ? os:getEnv("XERO_TIME_ENTRY_ID") : "9a8b7c6d-5e4f-3a2b-1c0d-e9f8a7b6c5d4";

@test:Config {groups: ["live_tests", "mock_tests"]}
function testListProjects() returns error? {
    ProjectList response = check xeroProjects->listProjects({xeroTenantId: tenantId});
    test:assertTrue((response.items ?: []).length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testCreateProject() returns error? {
    if isLiveServer {
        return;
    }
    Project response = check xeroProjects->createProject({xeroTenantId: tenantId}, {
        contactId: "1ed7e1ba-f6a2-4a4f-8b1c-3d5e6f7a8b90",
        name: "Website Redesign"
    });
    test:assertEquals(response.name, "Website Redesign");
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testGetProject() returns error? {
    Project response = check xeroProjects->getProject(PROJECT_ID, {xeroTenantId: tenantId});
    test:assertTrue(response.projectId is string);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testUpdateProject() returns error? {
    if isLiveServer {
        return;
    }
    check xeroProjects->updateProject(PROJECT_ID, {xeroTenantId: tenantId}, {name: "Website Redesign v2"});
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testUpdateProjectStatus() returns error? {
    if isLiveServer {
        return;
    }
    check xeroProjects->updateProjectStatus(PROJECT_ID, {xeroTenantId: tenantId}, {status: "CLOSED"});
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testListProjectUsers() returns error? {
    ProjectUserList response = check xeroProjects->listProjectUsers({xeroTenantId: tenantId});
    test:assertTrue((response.items ?: []).length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testListTasks() returns error? {
    TaskList response = check xeroProjects->listTasks(PROJECT_ID, {xeroTenantId: tenantId});
    test:assertTrue((response.items ?: []).length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testCreateTask() returns error? {
    if isLiveServer {
        return;
    }
    Task response = check xeroProjects->createTask(PROJECT_ID, {xeroTenantId: tenantId}, {
        name: "Design mockups",
        rate: {currency: "USD", value: 120},
        chargeType: "TIME",
        estimateMinutes: 480
    });
    test:assertEquals(response.name, "Design mockups");
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testGetTask() returns error? {
    Task response = check xeroProjects->getTask(PROJECT_ID, TASK_ID, {xeroTenantId: tenantId});
    test:assertTrue(response.taskId is string);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testUpdateTask() returns error? {
    if isLiveServer {
        return;
    }
    check xeroProjects->updateTask(PROJECT_ID, TASK_ID, {xeroTenantId: tenantId}, {
        name: "Design mockups",
        rate: {currency: "USD", value: 130},
        chargeType: "TIME"
    });
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testDeleteTask() returns error? {
    if isLiveServer {
        return;
    }
    Task created = check xeroProjects->createTask(PROJECT_ID, {xeroTenantId: tenantId}, {
        name: "Task to delete",
        rate: {currency: "USD", value: 100},
        chargeType: "TIME"
    });
    check xeroProjects->deleteTask(PROJECT_ID, created.taskId ?: TASK_ID, {xeroTenantId: tenantId});
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testListTimeEntries() returns error? {
    TimeEntryList response = check xeroProjects->listTimeEntries(PROJECT_ID, {xeroTenantId: tenantId});
    test:assertTrue((response.items ?: []).length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testCreateTimeEntry() returns error? {
    if isLiveServer {
        return;
    }
    TimeEntry response = check xeroProjects->createTimeEntry(PROJECT_ID, {xeroTenantId: tenantId}, {
        userId: "b1c2d3e4-f5a6-4789-9abc-def012345678",
        taskId: TASK_ID,
        dateUtc: "2026-10-05T09:00:00Z",
        duration: 90
    });
    test:assertTrue(response.timeEntryId is string);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testGetTimeEntry() returns error? {
    TimeEntry response = check xeroProjects->getTimeEntry(PROJECT_ID, TIME_ENTRY_ID, {xeroTenantId: tenantId});
    test:assertTrue(response.timeEntryId is string);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testUpdateTimeEntry() returns error? {
    if isLiveServer {
        return;
    }
    check xeroProjects->updateTimeEntry(PROJECT_ID, TIME_ENTRY_ID, {xeroTenantId: tenantId}, {
        userId: "b1c2d3e4-f5a6-4789-9abc-def012345678",
        taskId: TASK_ID,
        dateUtc: "2026-10-05T09:00:00Z",
        duration: 120
    });
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testDeleteTimeEntry() returns error? {
    if isLiveServer {
        return;
    }
    TimeEntry created = check xeroProjects->createTimeEntry(PROJECT_ID, {xeroTenantId: tenantId}, {
        userId: "b1c2d3e4-f5a6-4789-9abc-def012345678",
        taskId: TASK_ID,
        dateUtc: "2026-10-06T09:00:00Z",
        duration: 30
    });
    check xeroProjects->deleteTimeEntry(PROJECT_ID, created.timeEntryId ?: TIME_ENTRY_ID, {xeroTenantId: tenantId});
}
