[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "xero.projects"
version = "2.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Vendor/Xero", "Area/Finance & Accounting", "Type/Connector"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-xero.projects"

[build-options]
observabilityIncluded = true
