// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

# This is the Xero Projects API
public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string serviceUrl = "https://api.xero.com/projects.xro/2.0") returns error? {
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # Retrieves all projects
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK/success, returns a list of project objects 
    remote isolated function listProjects(ListProjectsHeaders headers, *ListProjectsQueries queries) returns ProjectList|error {
        string resourcePath = string `/Projects`;
        map<Encoding> queryParamEncoding = {"projectIds": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Create one or more new projects
    #
    # + headers - Headers to be sent with the request 
    # + payload - Create a new project with ProjectCreateOrUpdate object 
    # + return - OK/success, returns the new project object 
    remote isolated function createProject(CreateProjectHeaders headers, ProjectCreateOrUpdate payload) returns Project|error {
        string resourcePath = string `/Projects`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Retrieves a single project
    #
    # + projectId - You can specify an individual project by appending the projectId to the endpoint
    # + headers - Headers to be sent with the request 
    # + return - OK/success, returns the specified project object 
    remote isolated function getProject(string projectId, GetProjectHeaders headers) returns Project|error {
        string resourcePath = string `/Projects/${getEncodedUri(projectId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Updates a specific project
    #
    # + projectId - You can specify an individual project by appending the projectId to the endpoint
    # + headers - Headers to be sent with the request 
    # + payload - Request of type ProjectCreateOrUpdate 
    # + return - Success - return response 204 no content 
    remote isolated function updateProject(string projectId, UpdateProjectHeaders headers, ProjectCreateOrUpdate payload) returns error? {
        string resourcePath = string `/Projects/${getEncodedUri(projectId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, httpHeaders);
    }

    # Updates the status of a specific project
    #
    # + projectId - You can specify an individual project by appending the projectId to the endpoint
    # + headers - Headers to be sent with the request 
    # + payload - Update the status of an existing Project 
    # + return - Success - return response 204 no content 
    remote isolated function updateProjectStatus(string projectId, UpdateProjectStatusHeaders headers, ProjectPatch payload) returns error? {
        string resourcePath = string `/Projects/${getEncodedUri(projectId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, httpHeaders);
    }

    # Retrieves a list of all project users
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK/success, returns a list of project users 
    remote isolated function listProjectUsers(ListProjectUsersHeaders headers, *ListProjectUsersQueries queries) returns ProjectUserList|error {
        string resourcePath = string `/ProjectsUsers`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Retrieves all project tasks
    #
    # + projectId - You can specify an individual project by appending the projectId to the endpoint
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK/success, returns a list of task objects 
    remote isolated function listTasks(string projectId, ListTasksHeaders headers, *ListTasksQueries queries) returns TaskList|error {
        string resourcePath = string `/Projects/${getEncodedUri(projectId)}/Tasks`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Allows you to create a task
    #
    # + projectId - You can create a task on a specified projectId
    # + headers - Headers to be sent with the request 
    # + payload - The task object you are creating 
    # + return - OK/success, returns the new task object 
    remote isolated function createTask(string projectId, CreateTaskHeaders headers, TaskCreateOrUpdate payload) returns Task|error {
        string resourcePath = string `/Projects/${getEncodedUri(projectId)}/Tasks`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Retrieves a single project task
    #
    # + projectId - You can specify an individual project by appending the projectId to the endpoint
    # + taskId - You can specify an individual task by appending the taskId to the endpoint, i.e. GET https://.../tasks/{taskID}
    # + headers - Headers to be sent with the request 
    # + return - OK/success, returns the specified task object 
    remote isolated function getTask(string projectId, string taskId, GetTaskHeaders headers) returns Task|error {
        string resourcePath = string `/Projects/${getEncodedUri(projectId)}/Tasks/${getEncodedUri(taskId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Allows you to update a task
    #
    # + projectId - You can specify an individual project by appending the projectId to the endpoint
    # + taskId - You can specify an individual task by appending the id to the endpoint
    # + headers - Headers to be sent with the request 
    # + payload - The task object you are updating 
    # + return - OK/Success - return response 204 no content 
    remote isolated function updateTask(string projectId, string taskId, UpdateTaskHeaders headers, TaskCreateOrUpdate payload) returns error? {
        string resourcePath = string `/Projects/${getEncodedUri(projectId)}/Tasks/${getEncodedUri(taskId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, httpHeaders);
    }

    # Allows you to delete a task
    #
    # + projectId - You can specify an individual project by appending the projectId to the endpoint
    # + taskId - You can specify an individual task by appending the id to the endpoint
    # + headers - Headers to be sent with the request 
    # + return - Success - return response 204 no content 
    remote isolated function deleteTask(string projectId, string taskId, DeleteTaskHeaders headers) returns error? {
        string resourcePath = string `/Projects/${getEncodedUri(projectId)}/Tasks/${getEncodedUri(taskId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Retrieves all time entries associated with a specific project
    #
    # + projectId - Identifier of the project, that the task (which the time entry is logged against) belongs to
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - OK/success, returns a list of time entry objects 
    remote isolated function listTimeEntries(string projectId, ListTimeEntriesHeaders headers, *ListTimeEntriesQueries queries) returns TimeEntryList|error {
        string resourcePath = string `/Projects/${getEncodedUri(projectId)}/Time`;
        map<Encoding> queryParamEncoding = {"states": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Creates a time entry for a specific project
    #
    # + projectId - You can specify an individual project by appending the projectId to the endpoint
    # + headers - Headers to be sent with the request 
    # + payload - The time entry object you are creating 
    # + return - OK/success, returns the newly created time entry 
    remote isolated function createTimeEntry(string projectId, CreateTimeEntryHeaders headers, TimeEntryCreateOrUpdate payload) returns TimeEntry|error {
        string resourcePath = string `/Projects/${getEncodedUri(projectId)}/Time`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Retrieves a single time entry for a specific project
    #
    # + projectId - You can specify an individual project by appending the projectId to the endpoint
    # + timeEntryId - You can specify an individual time entry by appending the id to the endpoint
    # + headers - Headers to be sent with the request 
    # + return - OK/success, returns the specified time entry 
    remote isolated function getTimeEntry(string projectId, string timeEntryId, GetTimeEntryHeaders headers) returns TimeEntry|error {
        string resourcePath = string `/Projects/${getEncodedUri(projectId)}/Time/${getEncodedUri(timeEntryId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Updates a time entry for a specific project
    #
    # + projectId - You can specify an individual project by appending the projectId to the endpoint
    # + timeEntryId - You can specify an individual time entry by appending the id to the endpoint
    # + headers - Headers to be sent with the request 
    # + payload - The time entry object you are updating 
    # + return - Success - return response 204 no content 
    remote isolated function updateTimeEntry(string projectId, string timeEntryId, UpdateTimeEntryHeaders headers, TimeEntryCreateOrUpdate payload) returns error? {
        string resourcePath = string `/Projects/${getEncodedUri(projectId)}/Time/${getEncodedUri(timeEntryId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, httpHeaders);
    }

    # Deletes a time entry for a specific project
    #
    # + projectId - You can specify an individual project by appending the projectId to the endpoint
    # + timeEntryId - You can specify an individual task by appending the id to the endpoint
    # + headers - Headers to be sent with the request 
    # + return - Success - return response 204 no content 
    remote isolated function deleteTimeEntry(string projectId, string timeEntryId, DeleteTimeEntryHeaders headers) returns error? {
        string resourcePath = string `/Projects/${getEncodedUri(projectId)}/Time/${getEncodedUri(timeEntryId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }
}
