// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/constraint;
import ballerina/http;

# A user who can be assigned to project work
public type ProjectUser record {
    # Full name of the user
    string name?;
    # Identifier of the user of the project
    string userId?;
    # Email address of the user
    string email?;
};

# A task within a project with charge details
public type Task record {
    # Minutes logged against this task if its charge type is `FIXED`
    int fixedMinutes?;
    # Can be `TIME`, `FIXED` or `NON_CHARGEABLE`, defines how the task will be charged. Use `TIME` when you want to charge per hour and `FIXED` to charge as a fixed amount. If the task will not be charged use `NON_CHARGEABLE`
    ChargeType chargeType?;
    # Minutes on this task which have been invoiced
    int minutesInvoiced?;
    # Monetary amount with its currency
    Amount totalAmount?;
    # Monetary amount with its currency
    Amount amountInvoiced?;
    # Monetary amount with its currency
    Amount rate?;
    # Total minutes which have been logged against the task. Logged by assigning a time entry to a task
    int totalMinutes?;
    # Minutes on this task which have not been invoiced
    int minutesToBeInvoiced?;
    # Minutes logged against this task if its charge type is `NON_CHARGEABLE`
    int nonChargeableMinutes?;
    # Monetary amount with its currency
    Amount amountToBeInvoiced?;
    # Name of the task
    string name?;
    # An estimated time to perform the task
    int estimateMinutes?;
    # Identifier of the project task belongs to
    string projectId?;
    # Identifier of the task
    string taskId?;
    # Status of the task. When a task of ChargeType is `FIXED` and the rate amount is invoiced the status will be set to `INVOICED` and can't be modified. A task with ChargeType of `TIME` or `NON_CHARGEABLE` cannot have a status of `INVOICED`. A `LOCKED` state indicates that the task is currently changing state (for example being invoiced) and can't be modified
    "ACTIVE"|"INVOICED"|"LOCKED" status?;
};

# Represents the Queries record for the operation: listTimeEntries
public type ListTimeEntriesQueries record {
    # Finds all time entries for this contact identifier
    string contactId?;
    # ISO 8601 UTC date. Finds all time entries on or after this date filtered on the `dateUtc` field
    string dateAfterUtc?;
    # ISO 8601 UTC date. Finds all time entries on or before this date filtered on the `dateUtc` field
    string dateBeforeUtc?;
    # Optional, it is set to 50 by default. The number of items to return per page in a paged response - Must be a number between 1 and 500
    int pageSize?;
    # Finds all time entries for this invoice
    string invoiceId?;
    # Set to 1 by default. The requested number of the page in paged response - Must be a number greater than 0
    int page?;
    # The xero user identifier of the person who logged time
    string userId?;
    # Identifier of the task that time entry is logged against
    string taskId?;
    # Comma-separated list of states to find. Will find all time entries that are in the status of whatever is specified
    string[] states?;
    # Finds all time entries which relate to tasks with the charge type `TIME` or `FIXED`
    boolean isChargeable?;
};

# Represents the Headers record for the operation: updateTimeEntry
public type UpdateTimeEntryHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "Xero-Tenant-Id"}
    string xeroTenantId;
    # This allows you to safely retry requests without the risk of duplicate processing. 128 character max
    @http:Header {name: "Idempotency-Key"}
    string idempotencyKey?;
};

# Paged list of tasks
public type TaskList record {
    # Pagination details of a paged response
    Pagination pagination?;
    Task[] items?;
};

# Represents the Headers record for the operation: createTimeEntry
public type CreateTimeEntryHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "Xero-Tenant-Id"}
    string xeroTenantId;
    # This allows you to safely retry requests without the risk of duplicate processing. 128 character max
    @http:Header {name: "Idempotency-Key"}
    string idempotencyKey?;
};

# Represents the Headers record for the operation: getProject
public type GetProjectHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "Xero-Tenant-Id"}
    string xeroTenantId;
};

# Represents the Headers record for the operation: getTimeEntry
public type GetTimeEntryHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "Xero-Tenant-Id"}
    string xeroTenantId;
};

# 3 letter alpha code for the ISO-4217 currency code, e.g. USD, AUD
public type CurrencyCode "AED"|"AFN"|"ALL"|"AMD"|"ANG"|"AOA"|"ARS"|"AUD"|"AWG"|"AZN"|"BAM"|"BBD"|"BDT"|"BGN"|"BHD"|"BIF"|"BMD"|"BND"|"BOB"|"BRL"|"BSD"|"BTN"|"BWP"|"BYN"|"BZD"|"CAD"|"CDF"|"CHF"|"CLP"|"CNY"|"COP"|"CRC"|"CUC"|"CUP"|"CVE"|"CZK"|"DJF"|"DKK"|"DOP"|"DZD"|"EGP"|"ERN"|"ETB"|"EUR"|"FJD"|"FKP"|"GBP"|"GEL"|"GGP"|"GHS"|"GIP"|"GMD"|"GNF"|"GTQ"|"GYD"|"HKD"|"HNL"|"HRK"|"HTG"|"HUF"|"IDR"|"ILS"|"IMP"|"INR"|"IQD"|"IRR"|"ISK"|"JEP"|"JMD"|"JOD"|"JPY"|"KES"|"KGS"|"KHR"|"KMF"|"KPW"|"KRW"|"KWD"|"KYD"|"KZT"|"LAK"|"LBP"|"LKR"|"LRD"|"LSL"|"LYD"|"MAD"|"MDL"|"MGA"|"MKD"|"MMK"|"MNT"|"MOP"|"MRU"|"MUR"|"MVR"|"MWK"|"MXN"|"MYR"|"MZN"|"NAD"|"NGN"|"NIO"|"NOK"|"NPR"|"NZD"|"OMR"|"PAB"|"PEN"|"PGK"|"PHP"|"PKR"|"PLN"|"PYG"|"QAR"|"RON"|"RSD"|"RUB"|"RWF"|"SAR"|"SBD"|"SCR"|"SDG"|"SEK"|"SGD"|"SHP"|"SLL"|"SOS"|"SPL"|"SRD"|"STN"|"SVC"|"SYP"|"SZL"|"THB"|"TJS"|"TMT"|"TND"|"TOP"|"TRY"|"TTD"|"TVD"|"TWD"|"TZS"|"UAH"|"UGX"|"USD"|"UYU"|"UZS"|"VEF"|"VND"|"VUV"|"WST"|"XAF"|"XCD"|"XDR"|"XOF"|"XPF"|"YER"|"ZAR"|"ZMW"|"ZMK"|"ZWD";

# Payload to create or update a project
public type ProjectCreateOrUpdate record {
    # Deadline for the project. UTC Date Time in ISO-8601 format
    string deadlineUtc?;
    # Identifier of the contact this project was created for
    string contactId?;
    # Name of the project
    string name;
    decimal estimateAmount?;
};

# Pagination details of a paged response
public type Pagination record {
    # Set to 1 by default. The requested number of the page in paged response - Must be a number greater than 0.
    int page?;
    # Optional, it is set to 50 by default. The number of items to return per page in a paged response - Must be a number between 1 and 500.
    int pageSize?;
    # Number of pages available
    int pageCount?;
    # Number of items returned
    int itemCount?;
};

# Paged list of time entries
public type TimeEntryList record {
    # Pagination details of a paged response
    Pagination pagination?;
    TimeEntry[] items?;
};

# Represents the Queries record for the operation: listTasks
public type ListTasksQueries record {
    # Can be `TIME`, `FIXED` or `NON_CHARGEABLE`, defines how the task will be charged. Use `TIME` when you want to charge per hour and `FIXED` to charge as a fixed amount. If the task will not be charged use `NON_CHARGEABLE`
    ChargeType chargeType?;
    # Optional, it is set to 50 by default. The number of items to return per page in a paged response - Must be a number between 1 and 500
    int pageSize?;
    # Set to 1 by default. The requested number of the page in paged response - Must be a number greater than 0
    int page?;
    # Search for all tasks that match a comma separated list of taskIds, i.e. GET https://.../tasks?taskIds={taskID},{taskID}
    string taskIds?;
};

# Represents the Headers record for the operation: createTask
public type CreateTaskHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "Xero-Tenant-Id"}
    string xeroTenantId;
    # This allows you to safely retry requests without the risk of duplicate processing. 128 character max
    @http:Header {name: "Idempotency-Key"}
    string idempotencyKey?;
};

# Paged list of projects
public type ProjectList record {
    # Pagination details of a paged response
    Pagination pagination?;
    Project[] items?;
};

# OAuth2 Refresh Token Grant Configs
public type OAuth2RefreshTokenGrantConfig record {|
    *http:OAuth2RefreshTokenGrantConfig;
    # Refresh URL
    string refreshUrl = "https://identity.xero.com/connect/token";
|};

# Represents the Headers record for the operation: updateTask
public type UpdateTaskHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "Xero-Tenant-Id"}
    string xeroTenantId;
    # This allows you to safely retry requests without the risk of duplicate processing. 128 character max
    @http:Header {name: "Idempotency-Key"}
    string idempotencyKey?;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Configurations related to client authentication
    http:BearerTokenConfig|OAuth2RefreshTokenGrantConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

# Represents the Headers record for the operation: createProject
public type CreateProjectHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "Xero-Tenant-Id"}
    string xeroTenantId;
    # This allows you to safely retry requests without the risk of duplicate processing. 128 character max
    @http:Header {name: "Idempotency-Key"}
    string idempotencyKey?;
};

# Represents the Headers record for the operation: deleteTimeEntry
public type DeleteTimeEntryHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "Xero-Tenant-Id"}
    string xeroTenantId;
};

# Payload to create or update a task
public type TaskCreateOrUpdate record {
    # Monetary amount with its currency
    Amount rate;
    # Name of the task. Max length 100 characters
    string name;
    # Can be `TIME`, `FIXED` or `NON_CHARGEABLE`, defines how the task will be charged. Use `TIME` when you want to charge per hour and `FIXED` to charge as a fixed amount. If the task will not be charged use `NON_CHARGEABLE`
    ChargeType chargeType;
    # An estimated time to perform the task
    int estimateMinutes?;
};

# Represents the Headers record for the operation: getTask
public type GetTaskHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "Xero-Tenant-Id"}
    string xeroTenantId;
};

# Monetary amount with its currency
public type Amount record {
    # 3 letter alpha code for the ISO-4217 currency code, e.g. USD, AUD
    CurrencyCode currency?;
    decimal value?;
};

# Payload to create or update a time entry
public type TimeEntryCreateOrUpdate record {
    # Number of minutes to be logged. Duration is between 1 and 59940 inclusively
    int duration;
    # Date time entry is logged on. UTC Date Time in ISO-8601 format
    string dateUtc;
    # An optional description of the time entry, will be set to null if not provided during update
    string description?;
    # The xero user identifier of the person logging the time
    string userId;
    # Identifier of the task that time entry is logged against
    string taskId;
};

# Represents the Headers record for the operation: listTasks
public type ListTasksHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "Xero-Tenant-Id"}
    string xeroTenantId;
};

# Paged list of project users
public type ProjectUserList record {
    # Pagination details of a paged response
    Pagination pagination?;
    ProjectUser[] items?;
};

# Represents the Headers record for the operation: updateProjectStatus
public type UpdateProjectStatusHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "Xero-Tenant-Id"}
    string xeroTenantId;
    # This allows you to safely retry requests without the risk of duplicate processing. 128 character max
    @http:Header {name: "Idempotency-Key"}
    string idempotencyKey?;
};

# A Xero project with its invoicing and amount details
public type Project record {
    # Monetary amount with its currency
    Amount expenseAmountInvoiced?;
    # Monetary amount with its currency
    Amount depositApplied?;
    # Monetary amount with its currency
    Amount taskAmountInvoiced?;
    # Identifier of the contact this project was created for
    string contactId?;
    # Monetary amount with its currency
    Amount taskAmountToBeInvoiced?;
    # Monetary amount with its currency
    Amount expenseAmountToBeInvoiced?;
    # Monetary amount with its currency
    Amount totalTaskAmount?;
    # Monetary amount with its currency
    Amount projectAmountInvoiced?;
    # Deadline for the project. UTC Date Time in ISO-8601 format
    string deadlineUtc?;
    # Minutes which have not been invoiced across all chargeable tasks in the project
    int minutesToBeInvoiced?;
    # Monetary amount with its currency
    Amount creditNoteAmount?;
    # Name of the project
    string name;
    # Monetary amount with its currency
    Amount estimateAmount?;
    # Monetary amount with its currency
    Amount estimate?;
    # Monetary amount with its currency
    Amount deposit?;
    # Monetary amount with its currency
    Amount totalToBeInvoiced?;
    # Monetary amount with its currency
    Amount totalExpenseAmount?;
    # Identifier of the project
    string projectId?;
    # 3 letter alpha code for the ISO-4217 currency code, e.g. USD, AUD
    CurrencyCode currencyCode?;
    # Monetary amount with its currency
    Amount totalInvoiced?;
    # A total of minutes logged against all tasks on the Project
    int minutesLogged?;
    # Status for project
    ProjectStatus status?;
};

# Represents the Headers record for the operation: listProjectUsers
public type ListProjectUsersHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "Xero-Tenant-Id"}
    string xeroTenantId;
};

# Status for project
public type ProjectStatus "INPROGRESS"|"CLOSED";

# Represents the Headers record for the operation: updateProject
public type UpdateProjectHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "Xero-Tenant-Id"}
    string xeroTenantId;
    # This allows you to safely retry requests without the risk of duplicate processing. 128 character max
    @http:Header {name: "Idempotency-Key"}
    string idempotencyKey?;
};

# Represents the Queries record for the operation: listProjectUsers
public type ListProjectUsersQueries record {
    # Optional, it is set to 50 by default. The number of items to return per page in a paged response - Must be a number between 1 and 500
    @constraint:Int {minValue: 1, maxValue: 500}
    int pageSize = 50;
    # set to 1 by default. The requested number of the page in paged response - Must be a number greater than 0
    int page = 1;
};

# A time entry logged against a project task
public type TimeEntry record {
    # The duration of logged minutes
    int duration?;
    # The date time that time entry is logged on. UTC Date Time in ISO-8601 format
    string dateUtc?;
    # The date time that time entry is created. UTC Date Time in ISO-8601 format. By default it is set to server time
    string dateEnteredUtc?;
    # Identifier of the time entry
    string timeEntryId?;
    # A description of the time entry
    string description?;
    # The xero user identifier of the person who logged time
    string userId?;
    # Identifier of the project, that the task (which the time entry is logged against) belongs to
    string projectId?;
    # Identifier of the task that time entry is logged against
    string taskId?;
    # Status of the time entry. By default a time entry is created with status of `ACTIVE`. A `LOCKED` state indicates that the time entry is currently changing state (for example being invoiced). Updates are not allowed when in this state. It will have a status of INVOICED once it is invoiced
    "ACTIVE"|"LOCKED"|"INVOICED" status?;
};

# Can be `TIME`, `FIXED` or `NON_CHARGEABLE`, defines how the task will be charged. Use `TIME` when you want to charge per hour and `FIXED` to charge as a fixed amount. If the task will not be charged use `NON_CHARGEABLE`
public type ChargeType "TIME"|"FIXED"|"NON_CHARGEABLE";

# Represents the Queries record for the operation: listProjects
public type ListProjectsQueries record {
    # Filter for projects for a specific contact
    string contactID?;
    # Optional, it is set to 50 by default. The number of items to return per page in a paged response - Must be a number between 1 and 500
    @constraint:Int {minValue: 1, maxValue: 500}
    int pageSize = 50;
    # Search for all projects that match a comma separated list of projectIds
    string[] projectIds?;
    # set to 1 by default. The requested number of the page in paged response - Must be a number greater than 0
    int page = 1;
    # Filter for projects in a particular state (INPROGRESS or CLOSED)
    string states?;
};

# Represents the Headers record for the operation: deleteTask
public type DeleteTaskHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "Xero-Tenant-Id"}
    string xeroTenantId;
};

# Represents the Headers record for the operation: listProjects
public type ListProjectsHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "Xero-Tenant-Id"}
    string xeroTenantId;
};

# Represents the Headers record for the operation: listTimeEntries
public type ListTimeEntriesHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "Xero-Tenant-Id"}
    string xeroTenantId;
};

# Payload to change the status of a project
public type ProjectPatch record {
    # Status for project
    ProjectStatus status;
};
